name: Deploy Storybook to GitHub Pages
on:
  push:
    branches:
      - dev # 或者你要部署的分支
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: Build and Deploy
      run: npm run build-storybook && npm run deploy-storybook
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
